export const REQUEST_REPO = 'REQUEST_REPO';
export const RECEIVE_REPO = 'RECEIVE_REPO';
export const FAILURE_REPO = 'FAILURE_REPO';

export const REQUEST_LANGUAGE = 'REQUEST_LANGUAGE';
export const RECEIVE_LANGUAGE = 'RECEIVE_LANGUAGE';
export const FAILURE_LANGUAGE = 'FAILURE_LANGUAGE';
